# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='exchange',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
        ),
    ]
